### ISSUE TITLE
Change PID to 0xCC15

### ISSUE THREAD

**Issue by ghost** [rad1o/f1rmware#11]
Update https://github.com/rad1o/hackrf/blob/510dde748510dd83ed1402397e11e2cfd9117b91/firmware/hackrf_usb/usb_descriptor.c#L34 to use 0xCC15 since all the HackRF library files have been updated  to use this in the last commit (ref: https://github.com/mossmann/hackrf/pull/200/files).

**Comment by Sec42** [comment]
As far as I understand it, this would break the rad1o it for people using packaged gnuradio/osmocom from distributions like Ubuntu, right? That's why I want to wait a bit longer. Please correct me if I'm wrong about this.

**Comment by ghost** [comment]
For packages, yes you are right.

**Comment by Sec42** [comment]
schneider has done that yesterday.

**Comment by ghost** [comment]
Thanks
