### ISSUE TITLE
rgb_leds binary in campapp does not work

### ISSUE THREAD

**Issue by stackpivot** [rad1o/f1rmware#118]
When executing the rgb_leds binary and selecting one of the listed files the rgb_leds program is closed and im back in the menu. (LED colors are not changing)

Any clues what that could be?

**Comment by dos1** [comment]
Maybe you have rgbleds disabled in the config?

BTW. Check out #112

**Comment by stackpivot** [comment]
Damn, i'm sorry, that was exactly it.
