### ISSUE TITLE
"how to flash rad1o firmware" in readme

### ISSUE THREAD

**Issue by dergigo** [rad1o/f1rmware#13]
"make flash" requires the dfu-util that is marked optional above.

Please change the tutorial to something like this:

To flash the firmware permanently, simply copy the .bin file to the mounted mass storage rad1o.
If you want to just run the firmware once without permanently storing it on the rad1o, you will need the dfu-util mentioned above and run the "make flash" command.

**Comment by cko** [comment]
Thanks for noticing.
Maybe @schneider42 or @Sec42 can add you to the organization so you can change things yourself.

**Comment by schneider42** [comment]
I've invited @dergigo a few days ago, he still has to accept
