### ISSUE TITLE
Add 32c3 fahrplan

### ISSUE THREAD

**Issue by liliakai** [rad1o/f1rmware#134]
The rad1o contains a l0adable for the fahrplan from camp. I would like to have the schedule for 32c3 also. It looks like a pretty straightforward change to add this to the menu, but we need the equivalent of [`files/fahrplan.scd`](https://github.com/rad1o/f1rmware/blob/master/files/fahrplan.scd) for the congress. Does anyone have details on this file format or an easy way to generate it? Even a json endpoint or someother machine-parseable format to work off of would be helpful.

**Comment by ralphtheninja** [comment]
+1

**Comment by ikarus23** [comment]
Is [this](http://r0ket.de/fahrplan) helpful?

**Comment by liliakai** [comment]
Closing since this is not so relevant anymore. Maybe next year. ¯_(ツ)_/¯
