### ISSUE TITLE
Firmware built with toolchain from Ubuntu 17.10 and 18.04 doesn't work

### ISSUE THREAD

**Issue by steve-m** [rad1o/f1rmware#154]
Firmware that was build with gcc-arm-none-eabi 5.4.1+svn241155-1 and later that ships with Ubuntu 17.10 apparently produces a defective firmware image.
17.04 and 16.10 were not tested, but the toolchain from 16.04 works.

The firmware was flashed in DFU mode with smartflash, the FlashApp binary still seems to work, but the rad1o screen stays black after power reset, and booting into the MSC mode doesn't work as well.

**Comment by titodalcanton** [comment]
Same issue here, with gcc-arm-none-eabi 15:5.4.1+svn241155-1 from Debian 9.

**Comment by Sec42** [comment]
I can reproduce it, but don't yet know why.

**Comment by titodalcanton** [comment]
One more data point: building the l0dables works fine with gcc-arm-none-eabi 15:5.4.1+svn241155-1.

**Comment by Sec42** [comment]
I had completely forgotten about it. Sorry.

It should be fixed now with https://github.com/rad1o/f1rmware/commit/5ea3352f72f2a56da370f21b9c9aea72c50de70f

Please open a new issue if you still have issues.

**Comment by schneider42** [comment]
Thank you!
