### ISSUE TITLE
USB serial not working

### ISSUE THREAD

**Issue by jonnor** [rad1o/f1rmware#97]
Under https://github.com/rad1o/f1rmware/blob/master/doc/debugging.md it is mentioned that USB serial should be possible, and that the `testapp -> CDC` does something with this.

I tried to
- Run `udevadm monitor` on computer (Linux 4.1) to observe for devices being connected
- Power the rad1o, go into `testapp`, start `CDC`. Poke joystick around.

Expected:
- To see a serial device on computer.
- That CDC app writes something helpful to LCD screen

Actual:
- No serial devices is seen on computer.
- Nothing is shown on LCD screen (stays in menu)
- The rad1o freezes, need to reboot to go to another app

Tested both USB ports. Tested on two different devices. Running f1rmware from git. MSC mode works fine.

**Comment by jonnor** [comment]
Need this for [MicroFlo](http://microflo.org/) (a dataflow programming env I ported to radio), so I can live program it from host : )

**Comment by erikbos** [comment]
I have tried to use CDC as well, with both the rad1o library code and NXP's library code for the NXP4330. In both cases I could not get it to work: The VCP device does not appear on my laptop and the code appears to wait forever on a call to vcom_connected().

Also in the testapp's cdc tester does not work at first use, it hangs as well. It does work when starting the testapp, selecting msc, stopping msc, and then starting cdc. So it looks like the msc code initialises something cdc needs as well..

**Comment by jonnor** [comment]
@erikbos So when you run the msc code first, you see the serial device on laptop?

**Comment by erikbos** [comment]
Yes, the usb device appears on my Mac. "screen /dev/tty.usbmodem-<blabla>" connects to it and the cdc option in the demo app echos everything that I type back to me. Characters typed are echoed with bracket as the code is supposed to do, so it is not the local terminal doing the echoing.

**Comment by erikbos** [comment]
FYI: as work around in my rad1o app code I added:

```
MSCenable();
MSCdisable();
CDCenable();
```

to toggle MSC mode on and immediately off, followed by calling `CDCenable`: that appears to reliable setup the rad1o's for CDC.
